baseURL = "https://coadywing.github.io/"
languageCode = "en-us"
title = "Coady Wing"
theme = "avicenna"
#googleAnalytics = "UA-55873884-1"
timeout=3000

[params]
  subtitle= "Associate Professor -- O'Neill School, Indiana University Bloomington"
  interests="Health and Social Policy, Causal Inference"
  cv_name= "wing_cv.pdf"
  blog=""
  bio = "Coady Wing is an associate professor in the O'Neill School of Public and Environmental Affairs at Indiana University Bloomington. He studies health and social policy, with particular focus on health outcomes and behaviors and the delivery of health care services. He also conducts research on methodological topics related to program evaluation and causal inference. His research has been published in leading journals including Journal of Health Economics, American Journal of Health Economics, Health Affairs, Journal of Policy Analysis and Management, Journal of Human Resources, Demography, Brookings Papers on Economic Activity, Political Analysis, and the Proceedings of the National Academy of Sciences."
  GoogleScholar= "https://scholar.google.com/citations?user=T58Ty2gAAAAJ&hl=en"


[[params.affilation]]
  position = "Associate Professor"
  dept = "Indiana University Bloomington"
  name = "O'Neill School of Public and Environmental Affairs"
  contact = "cwing@indiana.edu"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/coady_wing"

[[params.social]]
  name = "Email"
  icon = "send"
  url = "mailto:cwing@indiana.edu"

[[params.publications]]
    year="Working Papers"
    cat_id="working"

[[params.publications.paper]]
    name = "Direct and indirect effects of vaccines: Evidence from Covid-19"
    authors = "Seth Freedman, Daniel Sacks, Kosali Simon, Coady Wing"
    nber_link = "https://www.nber.org/papers/w30550"
    link = "vaccine-spillovers.pdf"

[[params.publications.paper]]
    name = "Mortality effects of health care supply shocks: Evidence using linked deaths and electronic health records"
    authors = "Engy Ziedan, Kosali I. Simon, and Coady Wing"
    nber_link = "https://www.nber.org/papers/w30553"
    link = "mortality-cancelled-care.pdf"

[[params.publications.paper]]
    name = "How undervalued is the Covid-19 vaccine? Evidence from discrete choice experiments and VSL benchmarks"
    authors = "Patrick Carlin, Brian E. Dixon, Kosali I. Simon, Ryan Sullivan, and Coady Wing"
    nber_link = "https://www.nber.org/papers/w30118"
    link = "wtp-covid-vac.pdf"

[[params.publications.paper]]
      name = "Tactics for design and inference in synthetic control studies: An applied example using high-dimensional data"
      authors = "Alex Hollingsworth and Coady Wing"
      current_status_2  = ""
      current_status_1 = ""
      link = "https://doi.org/10.31235/osf.io/fc9xt"
      ungated_link = "https://doi.org/10.31235/osf.io/fc9xt"
      bonus = "[<font color='black'>[</font>R-package<font color='black'>]</font>](https://hollina.github.io/scul) [<font color='black'>[</font>Tutorial<font color='black'>]</font>](https://hollina.github.io/scul/articles/scul-tutorial.html) [<font color='black'>[</font>Slides<font color='black'>]</font>](hollingsworth_wing_scul_2020_presentation_ehec_2020.pdf)"
    

            

  
[[params.publications]]
year="Selected Publications"
cat_id="pubs"

[[params.publications.paper]]
      name = "What can we learn about SARS-CoV-2 Prevalence from Testing and Hospital Data?"
      authors = "Daniel Sacks, Nir Menachemi, Peter Embi, and Coady Wing"
      current_status_1  = "(Forthcoming)"
      current_status_2 = "__Review of Economics and Statistics__"
      link = "covid-prevalence-bounds.pdf" 
      
[[params.publications.paper]]
      name = "Societal disruptions and child mental health: Evidence from ADHD diagnosis during the Covid-19 pandemic"
      authors = "Seth M. Freedman, Kelli R. Marquardt, Dario Salcedo, Kosali I. Simon, and Coady Wing"
      current_status_1 = "(Forthcoming)"
      current_status_2 = "__Journal of Human Resources__"
      nber_link = "https://www.nber.org/papers/w30909"
      link = "adhd-covid.pdf" 

[[params.publications.paper]]
      name = "Comparative effects of recreational and medical marijuana laws on drug use among adults and adolescents"
      authors = "Hollingsworth, Alex., Coady Wing, and Ashley Bradford"
      current_status_1  = "(2022)"
      current_status_2 = "__Journal of Law and Economics__."
      link = "https://doi.org/10.1086/721267"
      
[[params.publications.paper]]
      name = "Determinants of disparities in Covid-19 job Losses"
      authors = "Laura Montenovo, Xuan Jiang, Felipe Lozano-Rojas, Ian Schmutte, Kosali I. Simon, Bruce A. Weinberg, and Coady Wing"
      current_status_1 = "(2022)"
      current_status_2 = "__Demography__"
      nber_link = "https://www.nber.org/papers/w27132"
      link = "https://read.dukeupress.edu/demography/article/59/3/827/307380/Determinants-of-Disparities-in-Early-COVID-19-Job" 

[[params.publications.paper]]
      name = "Tracking Public and Private Response to the Covid-10 Epidemic: Evidence from State and Local Government Actions"
      authors = "Sumedha Gupta, Thuy Nguyen, Shyam Ramen, Byungkyu Lee, Felipe Lozano-Rojas, Ana Bento, Kosali I. Simon, and Coady Wing"
      current_status_1 = "(2021)"
      current_status_2 = "__American Journal of Health Economics__"
      nber_link = "https://www.nber.org/papers/w27027"
      link = "https://www.journals.uchicago.edu/doi/full/10.1086/716197" 

[[params.publications.paper]]
      name = "Vaccinations against Covid-19 may have averted up to 140,000 deaths in the United States"
      authors = "Sumedha Gupta, Thuy Nguyen, Shyam Ramen, Byungkyu Lee, Felipe Lozano-Rojas, Ana Bento, Kosali I. Simon, and Coady Wing"
      current_status_1 = "(2021)"
      current_status_2 = "__Health Affairs__"
      nber_link = ""
      link = "https://www.healthaffairs.org/doi/10.1377/hlthaff.2021.00619" 

[[params.publications.paper]]
      name = "Effects of large gatherings on the Covid-10 epidemic: evidence from professional and college sports"
      authors = "Patrick Carlin, Paul Minard, Daniel Simon, and Coady Wing"
      current_status_1 = "(2021)"
      current_status_2 = "__Economics & Human Biology__"
      nber_link = ""
      link = "https://pubmed.ncbi.nlm.nih.gov/34298460/"

[[params.publications.paper]]
      name = "Mandated and voluntary social distancing during the Covid-19 epidemic"
      authors = "Sumedha Gupta, Kosali I. Simon, and Coady Wing"
      current_status_1 = "(2020)"
      current_status_2 = "__Brookings Papers on Economic Activity__"
      nber_link = ""
      link = "https://www.brookings.edu/articles/mandated-and-voluntary-social-distancing-during-the-covid-19-epidemic/" 

[[params.publications.paper]]
      name = "Evidence from internet search data shows information seeking responses to news of local Covid-19 cases"
      authors = "Ana Bento, Thuy Nguyen, Coady Wing, and Kosali I. Simon"
      current_status_1 = "(2020)"
      current_status_2 = "__Proceedings of the National Academy of Science__"
      nber_link = ""
      link = "https://www.pnas.org/doi/full/10.1073/pnas.2005335117" 


[[params.publications.paper]]
      name = "What can instrumental variables tell us about nonresponse in household surveys and political polls?"
      authors = "Coady Wing"
      current_status_1 = "(2019)"
      current_status_2 = "__Political Analysis__"
      nber_link = ""
      link = "https://www.cambridge.org/core/journals/political-analysis/article/what-can-instrumental-variables-tell-us-about-nonresponse-in-household-surveys-and-political-polls/8FFB5443B42B6B684EAD63E8D0DF03D8" 

[[params.publications.paper]]
      name = "Should we do more to police Medicaid fraud? Evidence on the intended and unintended consequences of expanded enforcement"
      authors = "Victoria Perez and Coady Wing"
      current_status_1 = "(2019)"
      current_status_2 = "__American Journal of Health Economics__"
      nber_link = ""
      link = "https://www.journals.uchicago.edu/doi/full/10.1162/ajhe_a_00130" 

[[params.publications.paper]]
      name = "Economic downturns and nurse attachment to federal employment"
      authors = "Danyao Li, Michael Richards, and Coady Wing"
      current_status_1 = "(2019)"
      current_status_2 = "__Health Economics__"
      nber_link = ""
      link = "https://pubmed.ncbi.nlm.nih.gov/31116501/" 

[[params.publications.paper]]
      name = "Designing difference in difference studies: best practices for public health policy research"
      authors = "Roberto Bello-Gomez, Kosali Simon, and Coady Wing"
      current_status_1 = "(2018)"
      current_status_2 = "__Annual Review of Public Health__"
      nber_link = ""
      link = "https://www.annualreviews.org/doi/abs/10.1146/annurev-publhealth-040617-013507" 


[[params.publications.paper]]
      name = "Relaxing occupational licensing requirements: Analyzing wages and prices for a medical service"
      authors = "Morris Kleiner, Allison Marier, KW Park, and Coady Wing"
      current_status_1 = "(2016)"
      current_status_2 = "__Journal of Law and Economics__"
      nber_link = ""
      link = "https://www.journals.uchicago.edu/doi/full/10.1086/688093" 
      
[[params.publications.paper]]
      name = "Effects of occupational regulations on the cost of dental services: evidence from dental insurance claims"
      authors = "Allison Marier and Coady Wing"
      current_status_1 = "(2014)"
      current_status_2 = "__Journal of Health Economics__"
      nber_link = ""
      link = "https://www.sciencedirect.com/science/article/pii/S0167629613001689" 

[[params.publications.paper]]
      name = "Strengthening the regression discontinuity design using additional design elements: A within-study comparison"
      authors = "Tom Cook and Coady Wing"
      current_status_1 = "(2013)"
      current_status_2 = "__Journal of Policy Analysis and Management__"
      nber_link = ""
      link = "https://onlinelibrary.wiley.com/doi/full/10.1002/pam.21721" 




[[params.publications]]
year="Teaching"
cat_id="teaching"

    [[params.publications.paper]]
    name = "SPEA-V 706 -- Statistics For Research in Public Affairs I (PhD Econometrics)"
    
    [[params.publications.paper]]
    name = "SPEA-V 707 -- Statistics For Research in Public Affairs II (PhD Econometrics)"
    
    [[params.publications.paper]]
    name = "SPEA-V 762 -- Public Program Evaluation"
    
    [[params.publications.paper]]
    name = "SPEA-V 723 -- Public Programs: Theory and Evidence"
    
    [[params.publications.paper]]
    name = "SPEA-V 379 -- Performance Measurement and Program Evaluation"
    
    [[params.publications.paper]]
    name = "SPEA-V 507 -- Data Analysis and Modeling (MPA Econometrics)"
    
    